# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tontines', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tontinecontribution',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tontine_contributions', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='tontinemembership',
            name='guarantor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tontine_guarantees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tontinemembership',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tontine_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tontinemembership',
            name='tontine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tontines.tontine'),
        ),
        migrations.AddIndex(
            model_name='tontine',
            index=models.Index(fields=['status', 'created_at'], name='tontines_to_status_b4c84f_idx'),
        ),
        migrations.AddIndex(
            model_name='tontinecontribution',
            index=models.Index(fields=['tontine', 'round_number'], name='tontines_to_tontine_9e2138_idx'),
        ),
        migrations.AddConstraint(
            model_name='tontinecontribution',
            constraint=models.UniqueConstraint(fields=('tontine', 'member', 'round_number'), name='unique_tontine_member_round'),
        ),
        migrations.AddConstraint(
            model_name='tontinemembership',
            constraint=models.UniqueConstraint(fields=('tontine', 'member'), name='unique_tontine_member'),
        ),
        migrations.AddConstraint(
            model_name='tontinemembership',
            constraint=models.UniqueConstraint(fields=('tontine', 'position'), name='unique_tontine_position'),
        ),
    ]
