# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('5000'))])),
                ('status', models.CharField(choices=[('active', 'active'), ('pending_withdrawal', 'pending_withdrawal'), ('withdrawn', 'withdrawn')], default='active', max_length=20)),
                ('return_rate', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=4)),
                ('total_returns_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawal_requested_at', models.DateTimeField(blank=True, null=True)),
                ('notice_period_days', models.IntegerField(default=7)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['investor', 'status'], name='investments_investo_5c61c8_idx')],
            },
        ),
    ]
