# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0001_initial'),
        ('tontines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal'), ('loan_disbursement', 'loan_disbursement'), ('loan_repayment', 'loan_repayment'), ('guarantee_block', 'guarantee_block'), ('guarantee_release', 'guarantee_release'), ('guarantee_seize', 'guarantee_seize'), ('commission_platform', 'commission_platform'), ('commission_guarantor', 'commission_guarantor'), ('commission_investor', 'commission_investor'), ('tontine_contribution', 'tontine_contribution'), ('tontine_payout', 'tontine_payout'), ('investment_deposit', 'investment_deposit'), ('investment_withdrawal', 'investment_withdrawal'), ('investment_return', 'investment_return'), ('tchekele_reward', 'tchekele_reward')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='loans.loan')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to=settings.AUTH_USER_MODEL)),
                ('tontine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tontines.tontine')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['sender', 'created_at'], name='transaction_sender__f6dfae_idx'), models.Index(fields=['receiver', 'created_at'], name='transaction_receive_f01bf5_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_68455c_idx'), models.Index(fields=['type', 'status'], name='transaction_type_983c49_idx')],
            },
        ),
    ]
