# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('bayam_sellam', 'bayam_sellam'), ('market', 'market'), ('training', 'training'), ('lottery', 'lottery'), ('other', 'other')], max_length=30)),
                ('discount_description', models.TextField()),
                ('tchekele_cost', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TchekeleRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_spent', models.IntegerField()),
                ('code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='rewards.partner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tchekele_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HonorBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^\\d{4}-\\d{2}$', 'format YYYY-MM')])),
                ('score', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honor_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['period', 'rank'], name='rewards_hon_period_6f970d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'period'), name='unique_honor_user_period')],
            },
        ),
    ]
