# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('commission', 'commission'), ('reserve_fund', 'reserve_fund'), ('investment_pool', 'investment_pool')], max_length=30, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
