# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000'))])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=4)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total_to_repay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('duration_days', models.IntegerField(choices=[(7, '7 jours'), (14, '14 jours'), (30, '30 jours'), (60, '60 jours'), (90, '90 jours')])),
                ('status', models.CharField(choices=[('waiting_guarantor', 'waiting_guarantor'), ('waiting_validation', 'waiting_validation'), ('active', 'active'), ('repaid', 'repaid'), ('defaulted', 'defaulted'), ('cancelled', 'cancelled')], default='waiting_guarantor', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('amount_repaid', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('grace_period_hours', models.IntegerField(default=72)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_as_borrower', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-requested_at',),
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_blocked', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('blocked', 'blocked'), ('released', 'released'), ('seized', 'seized')], default='blocked', max_length=20)),
                ('commission_earned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('guarantor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantees_given', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='loans.loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100'))])),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('wallet', 'wallet'), ('mtn_momo', 'mtn_momo'), ('orange_money', 'orange_money')], max_length=20)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
            ],
        ),
    ]
