# Generated by Django 5.1.4 on 2026-04-15 09:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('loan_reminder', 'loan_reminder'), ('loan_approved', 'loan_approved'), ('loan_cancelled', 'loan_cancelled'), ('loan_repaid', 'loan_repaid'), ('loan_defaulted', 'loan_defaulted'), ('guarantee_request', 'guarantee_request'), ('guarantee_seized', 'guarantee_seized'), ('tontine_turn', 'tontine_turn'), ('tontine_reminder', 'tontine_reminder'), ('tchekele_earned', 'tchekele_earned'), ('system', 'system')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
